#! /usr/bin/env node

var fs = require('fs');

function usage() {
    console.log('Usage: etpl2to3 <input file/directory> [outputfile file/directory]');
}

var inputFile = process.argv[2];
if (!inputFile) {
    usage();
    process.exit(0);
}

if (!fs.existsSync(inputFile)) {
    console.log('[ERROR] <input file/directory> is not exist!!');
    console.log();
    usage();
    process.exit(1);
}

var inputStat = fs.statSync(inputFile);
if (inputStat.isDirectory()) {
    console.log(inputFile + ' is directory!');
}
else {
    console.log(inputFile + ' is normal file!');
}
